version: '3.4'

services:
 db:
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=yourStrong1_2Password
   - MSSQL_PID=Express

 aplicationdddapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DataBase=DockerDb
    ports:
      - "8080:80"

 aplicationdddmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - WebApi=http://aplicationddd.api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro